# This is a basic workflow to help you get started with Actions

name: Build/upload release versions

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
#  push:
#    branches: [ "master" ]
#  pull_request:
#    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          submodules: 'true'
      - uses: subosito/flutter-action@v2.10.0
      
      - name: Build NPA
        run: |
          chmod 0777 $GITHUB_WORKSPACE/.github/build-npa
          $GITHUB_WORKSPACE/.github/build-npa

      - name: Decode Keystore
        env:
            ENCODED_STRING: ${{ secrets.KEYSTORE }}
        run: |
            TMP_KEYSTORE_FILE_PATH="${GITHUB_WORKSPACE}/android/app"
            echo $ENCODED_STRING | base64 -di > "${TMP_KEYSTORE_FILE_PATH}"/upload-keystore.jks
 
      - name: Build android appbundle
        run: flutter build appbundle
        env:
          SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
          SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }
          
      - name: Update google play
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
          packageName: net.ethrel.npa_mobile
          releaseFiles: build/app/outputs/bundle/release/app-release.aab
          track: production
          status: inProgress
          inAppUpdatePriority: 2
          userFraction: 0.33
          mappingFile: build/app/outputs/mapping/release/mapping.txt
          debugSymbols: build/app/intermediates/merged_native_libs/release/out/lib
          
      - name: Downloadable release store
        uses: actions/upload-artifact@v2
        with:
          name: Build Artifacts
          path: |
            build/app/outputs/bundle/release
            build/app/outputs/mapping/release/mapping.txt
            build/app/intermediates/merged_native_libs/release/out/lib
          retention-days: 1
